addSbtPlugin("org.scala-js"   % "sbt-scalajs"    % "1.10.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("com.github.sbt" % "sbt-release"    % "1.4.0")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"  % "2.0.10")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.12")
