addSbtPlugin("org.scala-js"   % "sbt-scalajs"    % "1.8.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.4.6")
addSbtPlugin("com.github.sbt" % "sbt-release"    % "1.1.0")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"  % "1.9.3")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.10")
