name: CI
on: [pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v13
      - name: Check Scalafmt/Scaladoc
        run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck nodejs_v14/doc core/doc
      - name: Install NPM deps
        run: npm install
      - name: Check README
        run: npm run lint-md
